# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-ubuntu:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with: { fetch-depth: 0 }
 
      - name: install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -qq ninja-build

      # Runs a single command using the runners shell
      - name: Gen project
        run:  python build/gen.py

      # Runs a set of commands using the runners shell
      - name: Build
        run: ninja -C out gn
      
      - name: Print gn version
        run: ./out/gn --version
      
      - name: Rename gn to gn_lin
        run: mv out/gn out/gn_lin

      - name: Upload gn_lin
        uses: actions/upload-artifact@v2.1.4
        with:
          path: out/gn_lin
          # The desired behavior if no files are found using the provided path.
            
  build-mac:
    # The type of runner that the job will run on
    runs-on: macOS-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with: { fetch-depth: 0 }
 
      - name: install dependencies
        run: brew install ninja

      # Runs a single command using the runners shell
      - name: Gen project
        run:  python build/gen.py

      # Runs a set of commands using the runners shell
      - name: Build
        run: ninja -C out gn
      
      - name: Print gn version
        run: ./out/gn --version
      
      - name: Rename gn to gn_mac
        run: mv out/gn out/gn_mac

      - name: Upload gn_mac
        uses: actions/upload-artifact@v2.1.4
        with:
          path: out/gn_mac
          # The desired behavior if no files are found using the provided path.

